services:
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager/data'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./logs:/var/log/nestjs
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      [
        'run',
        '--server.http.listen-addr=0.0.0.0:12345',
        '/etc/alloy/config.alloy',
      ]
    ports:
      - '12345:12345'
    depends_on:
      - loki

volumes:
  prometheus-data:
  grafana-storage:
